name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        run: npm test

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20s"

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Run frontend tests
        working-directory: ./client
        run: npm test

  e2e-tests:
    runs-on: ubuntu-latest

    services:
      web:
        image: nginx:latest
        ports:
          - 80:80

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Start backend server
        working-directory: ./backend
        run: npm start &

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Start frontend server
        working-directory: ./client
        run: npm start &

      - name: Run end-to-end tests
        working-directory: ./e2e
        run: npm install && npm test
